# Generated by Django 4.0.2 on 2022-03-15 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaluser',
            options={'managed': True},
        ),
    ]
