# Generated by Django 4.0.2 on 2022-04-13 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0003_shopcategory_shopproduct_alter_generaluser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sponsororg',
            table=None,
        ),
    ]
